### ISSUE TITLE
How to setup for Cloud Vision API

### ISSUE THREAD

**Issue by Kavya-choudhary** [teganburns/Cloud-Vision-API#1]
Installing of gRPC, Absei; and Protocol buffers is successfully done. But when I run the cloud-vision-api.cpp file, it is showing error with include files not found. Help me on this

**Comment by teganburns** [comment]
I don't think anything in this project is useable anymore. It's been 5 years since it's been updated. I would suggest going to the google cloud page and getting started there. 

https://cloud.google.com/vision/docs/setup

After that pick out one of their "[supported libraries](https://cloud.google.com/vision/docs/libraries)" and use that. I would suggest using their Python library, that would be the simplest if you're on a desktop IMO.
